# Generated by Django 6.0.4 on 2026-05-10 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='reviewrating',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='reviewrating',
            old_name='updated_date',
            new_name='updated_at',
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='store/products')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name': 'productgallery',
                'verbose_name_plural': 'product gallery',
            },
        ),
    ]
